<?php


use CTApi\CTClient;
use CTApi\CTConfig;
use PHPUnit\Framework\TestCase;

class TestCaseHttpMocked extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        CTConfig::setApiUrl("https://example.church.tools/");
        CTConfig::setApiKey("notnullapikey");
        CTClient::setClient(new CTClientMock());
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        // overwrite custom CTClientMock with default HTTP-Configuration
        CTClient::createClient();
    }
}