name: PHP coding standards

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress

    - name: Composer dump-autoload to load all files
      run: composer dump-autoload

    - name: Run codefixer
      run: composer run-script php-cs-fixer

    - name: Check if code are already generated
      uses: tj-actions/verify-changed-files@v8.8
      id: verify-changed-files
      with:
        files: |
          src
          tests

    - name: Run step only when files change.
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        core.setFailed('Inconsistent coding standards. Please run `composer run-script php-cs-fixer` locally and commit style.')